---
- name: OCP | Installing Base Packages
  hosts: all
  become: yes
  tasks:
    - name: Install base packages
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - wget
        - git
        - net-tools
        - bind-utils
        - iptables-services
        - bridge-utils
        - bash-completion
        - kexec-tools
        - sos
        - psacct

    - name: Update all packages
      package:
        name: "*"
        state: latest

    - name: Install OCP Packages and utils
      package:
        name: openshift-ansible
        state: latest

    #- name: Install OCP excluder
    #  package:
    #    name: "{{ item }}"
    #    state: latest
    #  with_items:
    #    - atomic-openshift-excluder
    #    - atomic-openshift-docker-excluder
#
#    - name: OCP unexclude
#      command: "{{ item }} unexclude"
#      with_items:
#        - atomic-openshift-excluder
#        - atomic-openshift-docker-excluder
