---
- hosts: nodes
  gather_facts: no
  become: yes
  tasks:

  - name: Remove openshift etcd and docker
    yum:
      name: "{{ item }}"
      state: absent
    with_items:
      - docker
      - openshift
      - openshift-*
      - etcd
      - docker
    ignore_errors: true

  - name: Remove configuration files and directories
    file:
      name: "{{ item }}"
      state: absent
    with_items:
      - /etc/origin
      - /var/lib/docker
      - /var/lib/origin
      - /etc/etcd
      - /var/lib/etcd
      - /etc/sysconfig/atomic*
      - /etc/sysconfig/docker*
      - /root/.kube/config
      - /etc/ansible/facts.d
      - /usr/share/openshift
      - /etc/pki/ca-trust/source/anchors/openshift*
      - /etc/openvswitch 
      - /var/log/openvswitch
      - /etc/systemd/system/docker.service.wants/atomic*
      - /etc/systemd/system/docker.service.wants/etcd*
      - /etc/systemd/system/docker.service.wants/openvswitch*
      - /var/lib/cni/networks/openshift-sdn
      - /tmp/ansible* 
      - /tmp/openshift* 
      - /tmp/tmp*
    ignore_errors: true

  - name: Delete leftover network interfaces
    command: nmcli device delete {{ item }}
    with_items:
      - br0
      - ovs-system
      - tun0
      - vxlan_sys_4789
    register: device
    changed_when: device.rc == 0
    failed_when: false

  - name: Remove all the rpmsave files
    command: "find / -name '*rpmsave' -delete"
    ignore_errors: true
