---
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "resource-limits" 
spec:
  limits:
    -
      type: "Pod"
      max:
        cpu: "200m" 
        memory: "1Gi" 
      min:
        cpu: "1m" 
        memory: "6Mi" 
